{
    'name': 'Patient Management System',
    'version': '1.0',
    'category': 'Extra Tools',
    'sequence': 10,
    'author': 'Dickson Perdanakusuma',
    'summary': 'Patient Management System',
    'depends': ['web', 'base', 'mail', 'account', 'sale', 'hr'],
    'website': "erplab.id",
    'images': ['static/description/icon.jpg'],
    'data': [
        'data/sequence.xml',
        'report/report_view.xml',
        'report/report_appointment_card.xml',
        'security/security_group.xml',
        'security/ir.model.access.csv',
        'views/main_menu.xml',
        'wizard/create_medical_service_invoice.xml',
        'wizard/open_appointment_queue.xml',
        'wizard/settings.xml',
        'views/patient_record.xml',
        'views/hospital_appointment.xml',
        'views/hospital_appointment_queue.xml',
        'views/outpatient_medical_record.xml',
        'views/hospital_patient_invoice.xml',
        'views/hospital_drugs.xml',
        'views/hospital_ir_attachment_view.xml',
        'views/hospital_medical_procedure_icd9.xml',
        'views/hospital_disease_icd10.xml',
        'views/hr_contract_inherit.xml',
        'views/res_partner.xml'
    ],
    'demo': [],
    'css': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}